apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: ReplicaSet
  metadata:
    name: psql-replica
    labels:
      name: psql-replica
    annotations:
      "federation.kubernetes.io/replica-set-preferences": |
          {
              "rebalance": true,
              "clusters": {
                  "london": {
                      "minReplicas": 1,
                      "maxReplicas": 2,
                      "weight": 1
                  },
                  "frankfurt": {
                      "minReplicas": 2,
                      "maxReplicas": 4,
                      "weight": 1
                  }
              }
          }
  spec:
    replicas: 6
    template:
      metadata:
        labels:
          name: psql-replica
        name: psql-replica
      spec:
        containers:
        - name: server
          image: "crunchydata/crunchy-postgres:centos7-9.5-1.2.2"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5432
            protocol: TCP
          env:
          - name: PGHOST
            value: /tmp
          - name: PG_MODE
            value: slave
          - name: PG_MASTER_HOST
            value: INSERT_MASTER_POD_IP
          - name: PG_MASTER_PORT
            value: "5432"
          - name: PG_MASTER_USER
            value: master
          - name: PG_MASTER_PASSWORD
            value: password
          - name: PG_USER
            value: testuser
          - name: PG_PASSWORD
            value: password
          - name: PG_DATABASE
            value: userdb
          - name: PG_ROOT_PASSWORD
            value: password
          volumeMounts:
          - mountPath: /pgdata
            name: pgdata
          - mountPath: /backup
            name: backup
            readOnly: true
        volumes:
        - emptyDir: {}
          name: pgdata
        - emptyDir: {}
          name: backup
- apiVersion: v1
  kind: Service
  metadata:
    name: psql-replica
    labels:
      name: psql-replica
  spec:
    type: ClusterIP
    ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
    selector:
      name: psql-replica
