# Default values for psql-master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "crunchydata/crunchy-postgres"
  tag: "centos7-9.5-1.2.2"
  pullPolicy: IfNotPresent
service:
  name: psql-master
  type: ClusterIP
  externalPort: 5432
  internalPort: 5432
